<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Prod</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9c54801c-d57d-404c-be15-6c167ec3650a</testSuiteGuid>
   <testCaseLink>
      <guid>1a8440a4-b130-4ae6-a129-e7009a97aadf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/01_Homepage/01_001_Check_Homepage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ca47e6a-7785-4b0e-8d0e-0dba419ec4aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81eac913-c673-4875-bdd6-3c0b67fbdcd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76734917-be08-4aa7-ba0a-69db28ae3e59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77932db9-435e-474e-a9ad-89270a0025cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_001_Sim_OVO</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>037c92a6-35d6-4b2a-b660-eb1e85654cca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0712d0f0-5dca-4149-8c0b-cfa0960a023f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9118b2b-a863-4dbc-810d-ecaf7068fe49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8328c78-4ca0-4f96-bd54-1e0661fe35c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_002_Sim_Gopay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dd8f250-8f05-4515-b555-b72b82287c24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d791ad0-abbb-4888-b58d-ad43222afcfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371d08fa-5c53-4c12-9289-20f9fd01a880</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e9178ab-b4c6-40f7-8c03-a39450348e26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_004_Sim_BCA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46440763-2779-4811-a2c4-f747f8bcd426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04112b8f-4d5b-453f-866d-81955f0b4c56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de54bfa3-ba34-40cf-aa38-7c6b2e59cdb8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a16e3358-729e-4fa2-8f39-33c9d56cb261</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_006_Sim_Smartgift</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aea9146-e289-4e3c-8473-1cfbd47a32b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b941010-8b2b-436b-891e-f03badf035be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fa72e9c-fded-4297-8907-d57d03995d28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfe44945-54f2-45b7-a97f-b663f980aaa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_007_Esim_OVO</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0a7f5a3-60e8-4743-8e31-6db137a4299f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5037d88-b8bb-4329-a81b-d85583c226f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e35e071-668e-49ba-bfce-6c872101fce3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>275f2cf8-1aa7-4791-be67-8af461a0a877</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_008_Esim_Gopay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2de3bf1-efcc-450d-ad08-a24939b28d27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bca41e40-917b-4a4c-a8ce-c43663afddcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f23e2c4-f9e1-4036-b469-0e60bfefe656</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10fc27b8-e547-4044-8053-2f9e6dea3117</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_010_Esim_BCA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>751d05b4-719f-4929-ad8b-82ec9f42b937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ec4e8bb-c930-4333-8c96-ecee3c2aef04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5c0838-b29d-4dd9-abd4-559d7351d096</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af33cbaa-aab1-4ba7-a103-89e98cbafcd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_012_Esim_Smartgift</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98046ea7-c900-45ed-bcfe-710f80d919c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>501604d9-7b62-4109-afb9-90e62f846dab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59af698f-86cd-4443-896a-0c0db3a14cea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7c2673e-820b-4456-9932-07a2d1d32e84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_013_Esim_InvalidNIK</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18bd1b6b-461c-4fe9-a175-45961f1d689d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23d484e2-db3c-4142-b6ad-0decc443b7cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ab98542-c23f-4f5c-9e3e-8c249b826bcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5af6aa7e-bc63-4113-a480-4909d6e3d317</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_014_Verify_InvalidEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c376809a-25cf-4b93-afc0-cedd5e4f66f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1beced2-5c08-4886-8576-542e558afeee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a349e274-c09a-4eab-a945-0d4bb0f60810</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6324d94-808c-401d-afcb-2e29ee0a3c2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/02_Order_SIM/02_015_Verify_InvalidPhoneNumber</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0adc9aac-7ba8-463a-adf6-decc61c461e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61f09fb5-826e-4c9c-911e-580eb621598f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4545355c-62a0-4843-87f8-05aae991c09e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf61a699-728e-44cb-8d5d-74da7dd8a532</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/03_TopUp/03_001_Topup_OVO</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>121e7d22-9d8b-42de-9ca5-29884d6af8d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a57bf55-0537-4660-ba7b-e99025bb58d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841f0357-58d6-41e6-8247-cc20af7af541</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a4feae6-d1ae-412b-b190-d7eb2e058c25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/03_TopUp/03_002_Topup_Gopay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d418e6e-7e5e-411f-9b25-165201bdf1f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c9f65d8-37ed-432b-ace5-1dca0e07e750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d200979-3243-49d1-8d2a-9988b413d17b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c4771ae-c9a5-4862-9fe4-ede45fce2d23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/05_Plan/05_002_Buy_AddOn_OVO</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f139f97b-3284-4155-82e8-4c788eddad0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9d38c33-0460-4ce2-8fb6-bc682d74bc3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79b919cc-d142-422f-bcc6-16abc29a0726</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbd7b07d-a4cc-427a-9b1b-1f49192096b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01_Test Cases/05_Plan/05_003_Buy_AddOn_Gopay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f4335cf-5d25-41de-b20d-bcb37624d9dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6499fe02-6e47-48b9-b75a-4663ef8715c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe99990c-5771-4d99-82d6-9003be29fd48</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
